### ISSUE TITLE
Crash if you download a playlist with a song that is not available in your country.

### ISSUE THREAD

**Issue by dekiller82** [ExtendLord/DeezLoader-Reborn#5]
Workaround: Make free deezer account > Copy the playlist to a new playlist on your account > Remove unavailable songs > Download

**Comment by MiiLee94** [comment]
Seems like it;s not only that, I deleted all the songs that weren't available from this playlist 
http://www.deezer.com/playlist/4032001802?utm_source=deezer&utm_content=playlist-4032001802&utm_term=460370651_1515927952&utm_medium=web
Then it downloaded around 30 songs and crashed, so I deleted the songs it downloaded from the playlist and tried again, it downloaded one song and crashed again. So I delete that one song it downloaded from the playlist and tried again, as I thought it crashed instantly, but if I copy the direct link to the song it crashed on and download it separately it works fine.

If you need any more info I'm here

**Comment by ExtendLord** [comment]
Referenced to #1

**Comment by ExtendLord** [comment]
@dekiller82 @MiiLee94 
d6dc6919616a8be743cb484a80099d85c6c5d459
Fixed

**Comment by dekiller82** [comment]
Thanks for working on it but it seems to still not work properly. I still get a crash when downloading the playlist. Win 10 x64. 3.0.1 http://www.deezer.com/nl/playlist/3727826982

**Comment by ExtendLord** [comment]
@dekiller82 @MiiLee94 I apologize for the problem.<br/>
It should be fixed now 486085129fd2c17eb72f55bfbef4555534b0479c <br/>
Please clone again the source and compile again, go and check to see if there is any problem.<br/>
Thank you for the report.<br/>

**Comment by dekiller82** [comment]
Eyyy seems to be fixed now 👍 Thank you.
